[swipe.commands.three]
left_up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
right_up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Walk Through Windows (Reverse)'"
left_down = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
right_down = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Walk Through Windows'"
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch One Desktop to the Right'"
right = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch One Desktop to the Left'"



[swipe.commands.four]
left_up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Next Layout'"
right_up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Next Layout'"
up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Move Up/Prev'"
left_down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Next Layout'"
right_down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Next Layout'"
down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Move Down/Next'"
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Move  Left'"
right = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Krohnkite: Move Right'"

[pinch.commands]
in = "xdotool key ctrl+minus"
out = "xdotool key ctrl+plus"

[pinch.settings]
threshold = 0.25
one_shot = false


[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false


