[swipe.commands.three]
left_up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
right_up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Walk Through Windows (Reverse)'"
left_down = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
right_down = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Walk Through Windows'"
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch One Desktop to the Right'"
right = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch One Desktop to the Left'"



[swipe.commands.four]
left_up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_next_layout'"
right_up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_next_layout'"
up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_move_window_to_upper_pos'"
left_down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_next_layout'"
right_down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_next_layout'"
down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_move_window_to_bottom_pos'"
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_move_window_to_left_pos'"
right = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'bismuth_move_window_to_right_pos'"

[pinch.commands]
in = "ydotool key ctrl+minus"
out = "ydotool key ctrl+plus"

[pinch.settings]
threshold = 0.25
one_shot = false


[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false


